namespace MyCloudSync.App.Forms;

partial class SettingsForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        lblLocal = new Label();
        txtLocalPath = new TextBox();
        btnBrowseLocal = new Button();
        lblDrive = new Label();
        txtDriveFolder = new TextBox();
        btnChooseDrive = new Button();
        grpMode = new GroupBox();
        rbTwoWay = new RadioButton();
        rbUploadOnly = new RadioButton();
        rbDownloadOnly = new RadioButton();
        lblInterval = new Label();
        numInterval = new NumericUpDown();
        lblExclude = new Label();
        txtExclude = new TextBox();
        chkAutostart = new CheckBox();
        chkStartMinimized = new CheckBox();
        btnSave = new Button();
        btnCancel = new Button();
        grpMode.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numInterval).BeginInit();
        SuspendLayout();
        lblLocal.AutoSize = true;
        lblLocal.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblLocal.Location = new Point(20, 18);
        lblLocal.Name = "lblLocal";
        lblLocal.Text = "Локальна папка";
        txtLocalPath.Location = new Point(20, 40);
        txtLocalPath.Name = "txtLocalPath";
        txtLocalPath.Size = new Size(320, 23);
        txtLocalPath.ReadOnly = true;
        btnBrowseLocal.Location = new Point(350, 39);
        btnBrowseLocal.Name = "btnBrowseLocal";
        btnBrowseLocal.Size = new Size(90, 25);
        btnBrowseLocal.Text = "Огляд...";
        btnBrowseLocal.UseVisualStyleBackColor = true;
        btnBrowseLocal.Click += btnBrowseLocal_Click;
        lblDrive.AutoSize = true;
        lblDrive.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblDrive.Location = new Point(20, 75);
        lblDrive.Name = "lblDrive";
        lblDrive.Text = "Папка Google Drive";
        txtDriveFolder.Location = new Point(20, 97);
        txtDriveFolder.Name = "txtDriveFolder";
        txtDriveFolder.Size = new Size(320, 23);
        txtDriveFolder.ReadOnly = true;
        btnChooseDrive.Location = new Point(350, 96);
        btnChooseDrive.Name = "btnChooseDrive";
        btnChooseDrive.Size = new Size(90, 25);
        btnChooseDrive.Text = "Вибрати...";
        btnChooseDrive.UseVisualStyleBackColor = true;
        btnChooseDrive.Click += btnChooseDrive_Click;
        grpMode.Controls.Add(rbTwoWay);
        grpMode.Controls.Add(rbUploadOnly);
        grpMode.Controls.Add(rbDownloadOnly);
        grpMode.Location = new Point(460, 18);
        grpMode.Name = "grpMode";
        grpMode.Size = new Size(190, 105);
        grpMode.TabStop = false;
        grpMode.Text = "Режим";
        rbTwoWay.AutoSize = true;
        rbTwoWay.Location = new Point(12, 24);
        rbTwoWay.Name = "rbTwoWay";
        rbTwoWay.Checked = true;
        rbTwoWay.TabStop = true;
        rbTwoWay.Text = "Двостороння";
        rbTwoWay.UseVisualStyleBackColor = true;
        rbUploadOnly.AutoSize = true;
        rbUploadOnly.Location = new Point(12, 49);
        rbUploadOnly.Name = "rbUploadOnly";
        rbUploadOnly.Text = "Лише вивантаження";
        rbUploadOnly.UseVisualStyleBackColor = true;
        rbDownloadOnly.AutoSize = true;
        rbDownloadOnly.Location = new Point(12, 74);
        rbDownloadOnly.Name = "rbDownloadOnly";
        rbDownloadOnly.Text = "Лише завантаження";
        rbDownloadOnly.UseVisualStyleBackColor = true;
        lblInterval.AutoSize = true;
        lblInterval.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblInterval.Location = new Point(20, 140);
        lblInterval.Name = "lblInterval";
        lblInterval.Text = "Інтервал перевірки, хв";
        numInterval.Location = new Point(20, 162);
        numInterval.Name = "numInterval";
        numInterval.Size = new Size(120, 23);
        numInterval.Minimum = 1;
        numInterval.Maximum = 60;
        numInterval.Value = 5;
        lblExclude.AutoSize = true;
        lblExclude.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblExclude.Location = new Point(200, 140);
        lblExclude.Name = "lblExclude";
        lblExclude.Text = "Виключення за маскою";
        txtExclude.Location = new Point(200, 162);
        txtExclude.Name = "txtExclude";
        txtExclude.Size = new Size(240, 23);
        txtExclude.Text = "*.tmp; ~$*";
        chkAutostart.AutoSize = true;
        chkAutostart.Location = new Point(20, 205);
        chkAutostart.Name = "chkAutostart";
        chkAutostart.Text = "Запускати разом із Windows";
        chkAutostart.UseVisualStyleBackColor = true;
        chkStartMinimized.AutoSize = true;
        chkStartMinimized.Location = new Point(20, 232);
        chkStartMinimized.Name = "chkStartMinimized";
        chkStartMinimized.Text = "Запускати згорнутим у трей";
        chkStartMinimized.UseVisualStyleBackColor = true;
        btnSave.Location = new Point(440, 265);
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(100, 32);
        btnSave.Text = "Зберегти";
        btnSave.UseVisualStyleBackColor = true;
        btnSave.Click += btnSave_Click;
        btnCancel.Location = new Point(550, 265);
        btnCancel.Name = "btnCancel";
        btnCancel.Size = new Size(100, 32);
        btnCancel.Text = "Скасувати";
        btnCancel.UseVisualStyleBackColor = true;
        btnCancel.DialogResult = DialogResult.Cancel;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(670, 315);
        FormBorderStyle = FormBorderStyle.FixedSingle;
        MaximizeBox = false;
        StartPosition = FormStartPosition.CenterParent;
        MinimizeBox = false;
        AcceptButton = btnSave;
        CancelButton = btnCancel;
        Text = "Налаштування";
        grpMode.ResumeLayout(false);
        grpMode.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numInterval).EndInit();
        Controls.Add(lblLocal);
        Controls.Add(txtLocalPath);
        Controls.Add(btnBrowseLocal);
        Controls.Add(lblDrive);
        Controls.Add(txtDriveFolder);
        Controls.Add(btnChooseDrive);
        Controls.Add(grpMode);
        Controls.Add(lblInterval);
        Controls.Add(numInterval);
        Controls.Add(lblExclude);
        Controls.Add(txtExclude);
        Controls.Add(chkAutostart);
        Controls.Add(chkStartMinimized);
        Controls.Add(btnSave);
        Controls.Add(btnCancel);
        ResumeLayout(false);
        PerformLayout();
    }

    private Label lblLocal;
    private TextBox txtLocalPath;
    private Button btnBrowseLocal;
    private Label lblDrive;
    private TextBox txtDriveFolder;
    private Button btnChooseDrive;
    private GroupBox grpMode;
    private RadioButton rbTwoWay;
    private RadioButton rbUploadOnly;
    private RadioButton rbDownloadOnly;
    private Label lblInterval;
    private NumericUpDown numInterval;
    private Label lblExclude;
    private TextBox txtExclude;
    private CheckBox chkAutostart;
    private CheckBox chkStartMinimized;
    private Button btnSave;
    private Button btnCancel;
}
